redis:
  address: localhost
  port: 6379
  channel: SIMULATOR
simulator:
  name: "1000Genome-10ch-100k"
  nodes: 4
  vcpu: 48
  cache_factor: 0.5
  divisor: 5
  bandwith: 0.35 #Gb/s
  delay: 0 #s
  cache:
    enabled: true
    size: 5000 #MB
    policy: 'FIFO'
