redis:
  address: localhost
  port: 6379
  channel: SIMULATOR
simulator:
  name: "1000Genome-10ch-100k"
  nodes: 4
  #cache_size: 5000
  vcpu: 48
  cache_factor: 0.5
  divisor: 1
  bandwith: 1.5 #Gb/s
  delay: 0
  cache:
    enabled: false
    size: 5000
    policy: 'FIFO'
