redis:
  address: localhost
  port: 6379
  channel: SIMULATOR
simulator:
  name: "1000Genome-22ch-250k"
  nodes: 5
  vcpu: 48
  cache_factor: 0.5
  divisor: 1
  bandwith: 1.5 #Gb/s
  delay: 0 #s
  cache:
    enabled: true
    size: 5000 #MB
    policy: 'Belady'
